version: 0.2
env:
  variables:
    S3_BUCKET: "superkid.com.ua"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
     - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist/superkid-webapp s3://${S3_BUCKET} --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
